### ISSUE TITLE
Automate deployment to docs.lazyledger.org with GitHub action

### ISSUE THREAD

**Issue by liamsi** [lazyledger/lazyledger-specs#134]
Either the autom. deployment to docs.lazyledger.org doesn't work, or, the gitter badge shows up for other reasons?
![image](https://user-images.githubusercontent.com/7441766/109860664-b592d100-7c5e-11eb-8c7c-4081e4ddb284.png)

**Comment by musalbas** [comment]
There is no automatic deployment to docs.lazyledger.org. I has to be deployed manually. I could setup a cron job for it, or something, in the future.

**Comment by adlerjohn** [comment]
GitHub action would probably be ideal

**Comment by marbar3778** [comment]
What tool is being used to build the docs? I cant find a command to run the build.

**Comment by liamsi** [comment]
IMO, this is still relevant as we need something rendered and searchable deployed which is up to date.

**Comment by adlerjohn** [comment]
Specs are now automatically deployed to https://lazyledger.github.io/lazyledger-specs (https://github.com/lazyledger/lazyledger-specs/runs/2711676828) via GitHub actions. ref: #167

We can close this issue for now since it nice-looking docs are automatically deployed _somewhere_. Integration of multiple docs into a single location (e.g. docs.lazyledger.org) is an orthogonal issue that can be worked on later if needed.
